version: '3'

services:
  app:
    build: .
    volumes: 
      - .:/usr/src
    networks:
      - nginx_network

  nginx:
    image: nginx:1.15.6-alpine
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - .:/usr/src/app
    depends_on:
      - app
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge


