# Generated by Django 2.1.3 on 2018-11-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaser_name', models.CharField(max_length=200)),
                ('item_description', models.CharField(max_length=400)),
                ('item_price', models.IntegerField(default=0)),
                ('purchase_count', models.IntegerField(default=1)),
                ('merchant_address', models.CharField(max_length=600)),
                ('merchant_name', models.CharField(max_length=400)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
