# Generated by Django 2.1.3 on 2018-11-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaddata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
